same change find with email
WildCodeSchool/level-up-tasks-backend pull request #14
Opened 2024-07-08 14:52 UTC by sirinebettaieb

2024-07-08 15:07 UTC, Fatimata-dev approved these changes

2024-07-09 07:38 UTC, Benja-san requested changes

2024-07-09 07:38 UTC, Benja-san commented on src/main/java/com/leveluptasks/service/GroupService.java
> +        return "OK";
better return the group itself if you want to display it, or at least a response entity. Beter than a simple String

2024-07-09 07:38 UTC, Benja-san commented on src/main/java/com/leveluptasks/service/GroupService.java
> +        return groupRepository.save(new Groupe(groupCreationDTO.getGroupName()));
well, am not sure you are updating the groupe doing this

2024-07-09 12:58 UTC, Benja-san requested changes

2024-07-09 12:58 UTC, Benja-san commented on src/main/java/com/leveluptasks/controller/GroupController.java
> +     @PutMapping("/{id}/addUser")
postmapping if you add a new user

2024-07-09 12:58 UTC, Benja-san commented on src/main/java/com/leveluptasks/controller/GroupController.java
> +    public Groupe addUseGroupe( @RequestBody List<String> UserEmail, @PathVariable Long id) throws NoSuchAlgorithmException {
addUserToGroup

2024-07-09 12:58 UTC, Benja-san commented on src/main/java/com/leveluptasks/dto/GroupCreationDTO.java
> +    private List<String> userEmail;
userEmails with s if you create a list

2024-07-09 17:02 UTC, Benja-san requested changes

2024-07-09 17:02 UTC, Benja-san commented on src/main/java/com/leveluptasks/service/GroupService.java
> +        System.out.println( UserEmail);
remove debug prints

2024-07-09 17:02 UTC, Benja-san commented on src/main/java/com/leveluptasks/service/GroupService.java
> +        System.out.println( groupe);
remove debug prints

2024-07-09 17:14 UTC, Benja-san requested changes

2024-07-09 17:14 UTC, Benja-san commented on src/main/java/com/leveluptasks/service/GroupService.java
>          System.out.println( groupe);
still one

2024-07-10 08:47 UTC, Benja-san approved these changes

2024-07-10 08:56 UTC, merged